### ISSUE TITLE
depack的疑问

### ISSUE THREAD

**Issue by mistaker** [gislu/goSocketServer#4]
如果第一次读到的是   header  xxxx 123123123 header xxxx
第二次读到的是  123123123
这样子第二次的数据是不是会丢失了？

**Comment by gislu** [comment]
是的，因为这只是一个demo，所以在通讯协议里我只是写出了自定义通讯协议的思路，并没有对异常进行太多处理，实际应用中需要另外写一些异常处理逻辑 ： ）
另外因为出国后更换了手机好，之前那个csdn的账号已经无法登陆了，也没法修改文章或者回复评论，就比较蛋疼。。。
